import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest",
  display: "swap",
});

export const metadata: Metadata = {
  title: "purepool",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${onest.variable} font-['Onest'] h-full antialiased`}
    >
      <body className={`${onest.className} min-h-full flex flex-col bg-background-color! font-['Onest']`}>
        {children}
      </body>
    </html>
  );
}
